### ISSUE TITLE
update adblock list

### ISSUE THREAD

**Issue by kloudxyz** [luxysiv/Cloudflare-Gateway-Pihole#23]
How to setup auto update for the workflow so that adblock lists keeps updated with latest.

**Comment by luxysiv** [comment]
Adblock lists will update at 19h10 every day

**Comment by kloudxyz** [comment]
Great, i like your script.
Also really fast updating the blocklist :)

**Comment by luxysiv** [comment]
Thanks

**Comment by kloudxyz** [comment]
can you alos add the option to add ddns.
I want to create like 3 home router profiles in cloudflare,so their dynamic ip should be updated automaticaly in cloudflare.
I already have ddns with noip.

**Comment by luxysiv** [comment]
On Github has some repository supported it. Please search

**Comment by kloudxyz** [comment]
ok
