### ISSUE TITLE
fork update issue

### ISSUE THREAD

**Issue by suricloud** [luxysiv/Cloudflare-Gateway-Pihole#25]
Hi,

Please fix this issue, so we can update  normally.

This branch has conflicts that must be resolved
Discard 112 commits to make this branch match the upstream repository. 112 commits will be removed from this branch.

You can resolve merge conflicts using the command line and a text editor.

**Comment by luxysiv** [comment]
Sorry for the inconvenience, the current script has been completed so there will be no changes in the future.  You can update your branch and revise your list.  Best regards
