### ISSUE TITLE
adblock list style

### ISSUE THREAD

**Issue by suricloud** [luxysiv/Cloudflare-Gateway-Pihole#26]
Hi,

Are these format block list allowed to use with cloudflare?
Are then any performance issue when using this adblock format or the wildcard domain only format ?

https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/multi.txt

**Comment by luxysiv** [comment]
This kind was supported. Actually, my script up wildcard domain to CF. So list use wildcard domain is best. See default adlist.ini

**Comment by suricloud** [comment]
i see you adde this block list : Adhell = https://gitlab.com/fusionjack/adhell3-hosts/-/raw/master/hosts
Is it updated frequently ?

**Comment by luxysiv** [comment]
> i see you adde this block list : Adhell = https://gitlab.com/fusionjack/adhell3-hosts/-/raw/master/hosts Is it updated frequently ?

Yes. It be used for Samsung Knox

**Comment by suricloud** [comment]
> This kind was supported. Actually, my script up wildcard domain to CF. So list use wildcard domain is best. See default adlist.ini

i see on other forums they recommend to use hosts format?
eg this : https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
Is this supported on your script with cf too ?

**Comment by luxysiv** [comment]
> > This kind was supported. Actually, my script up wildcard domain to CF. So list use wildcard domain is best. See default adlist.ini
> 
> i see on other forums they recommend to use hosts format? eg this : https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt Is this supported on your script with cf too ?

Yes
