### ISSUE TITLE
Dynamic AdBlock rules

### ISSUE THREAD

**Issue by asterriya** [luxysiv/Cloudflare-Gateway-Pihole#35]
I download list from here https://github.com/cbuijs/hblock and upload all domains into here https://github.com/asterriya/Cloudflare-Gateway-Pihole/blob/main/lists/dynamic_blacklist.txt

So now all domains will be included as rules, or how is it going?

**Comment by luxysiv** [comment]
Every domain you add to dynamic_blacklist.txt will be a rule to block

**Comment by asterriya** [comment]
Yeah. I added custom rules, and it was updated but analytics section still saying that: To block queries, add a policy.

Seems like it thinking that rules is absent. I didn't add list rules.

**Comment by luxysiv** [comment]
Can you show me your list?

**Comment by luxysiv** [comment]
It works fine
![Screenshot_2024-05-30-05-34-53-108_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/636ace5c-e8d7-4472-b751-7cd7c6b5ba79)
![Screenshot_2024-05-30-05-33-45-694_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/7d7e9b27-50b1-4311-ab5b-07ca12071f7d)
![Screenshot_2024-05-30-05-33-24-191_com microsoft emmx canary](https://github.com/luxysiv/Cloudflare-Gateway-Pihole/assets/46205571/e84b86bf-41cf-4b97-84e3-8e6e83d2929c)

**Comment by asterriya** [comment]
Weird. Is there any cap for lines in dynamic AdBlock list?

**Comment by asterriya** [comment]
Found issue. It's all about cap limit for lines. No more than 300k. Will be good if you can mention that on your README file for others.

**Comment by luxysiv** [comment]
So sorry. I was notice but by my native language

**Comment by asterriya** [comment]
Yeah. Just add it to English language too :)
