### ISSUE TITLE
Rules issue

### ISSUE THREAD

**Issue by LexterS999** [luxysiv/Cloudflare-Gateway-Pihole#46]
I have final domains: 142028, but it's creating 254 rules. And must create 142 rules. Even deleting rules from Cloudflare Zero Trust doesn't help for this. Using list created by my script —https://raw.githubusercontent.com/LexterS999/DomainFormatter/main/data/output.txt. Until yesterday, everything was fine. But after last few updates of Cloudflare-Gateway-Pihole this issue start to appear.

**Comment by luxysiv** [comment]
It's not a bug, it's a feature of the script. The new script is based on dissecting domains and rearranging them to fill the list. If you run the create script to 254 and then run 142, the number of lists will still be 254. Later, the number of lists increases to more than 142, then the number of existing lists will be used gradually. This helps domains when uploaded to Cloudflare Gateway take effect immediately, without having to wait for rule updates. If you want to delete the excess lists and return to exactly 142, you can use a script with the old logic.

**Comment by luxysiv** [comment]
Copy and paste code below into __main__.py
```python
import argparse
from src.domains import DomainConverter
from src.cloudflare import (
    get_lists, get_rules, create_list, update_list, create_rule, 
    update_rule, delete_list, delete_rule, get_list_items
)
from src import utils, info, error, silent_error, PREFIX


class CloudflareManager:
    def __init__(self, prefix):
        self.list_name = f"[{prefix}]"
        self.rule_name = f"[{prefix}] Block Ads"

    def update_resources(self):
        domains_to_block = DomainConverter().process_urls()
        if len(domains_to_block) > 300000:
            error("The domains list exceeds Cloudflare Gateway's free limit of 300,000 domains.")
        
        current_lists = get_lists(self.list_name)
        current_rules = get_rules(self.rule_name)

        chunked_domains = list(utils.split_domain_list(domains_to_block, 1000))
        list_ids = []

        for index, chunk in enumerate(chunked_domains, start=1):
            list_name = f"{self.list_name} - {index:03d}"
            
            cgp_list = next((lst for lst in current_lists if lst["name"] == list_name), None)

            if cgp_list:
                current_values = get_list_items(cgp_list["id"])
                remove_items = set(current_values) - set(chunk)
                append_items = set(chunk) - set(current_values)

                if not remove_items and not append_items:
                    silent_error(f"Skipping list update: {cgp_list['name']}")
                else:
                    update_list(cgp_list["id"], remove_items, append_items)
                    info(f"Updated list: {cgp_list['name']}")
                list_ids.append(cgp_list["id"])
            else:
                lst = create_list(list_name, chunk)
                info(f"Created list: {lst['name']}")
                list_ids.append(lst["id"])

        # Extract existing list IDs from current_rules for comparison
        cgp_rule = next((rule for rule in current_rules if rule["name"] == self.rule_name), None)
        cgp_list_ids = utils.extract_list_ids(cgp_rule)

        if cgp_rule:
            if set(list_ids) == cgp_list_ids:
                silent_error(f"Skipping rule update as list IDs are unchanged: {cgp_rule['name']}")
            else:
                update_rule(self.rule_name, cgp_rule["id"], list_ids)
                info(f"Updated rule {cgp_rule['name']}")
        else:
            rule = create_rule(self.rule_name, list_ids)
            info(f"Created rule {rule['name']}")

        # Delete excess lists
        excess_lists = [lst for lst in current_lists if lst["id"] not in list_ids]
        for lst in excess_lists:
            delete_list(lst["id"])
            info(f"Deleted excess list: {lst['name']}")

    def delete_resources(self):
        current_lists = get_lists(self.list_name)
        current_rules = get_rules(self.rule_name)
        current_lists.sort(key=utils.safe_sort_key)

        # Delete rules with the name rule_name
        for rule in current_rules:
            delete_rule(rule["id"])
            info(f"Deleted rule: {rule['name']}")

        # Delete lists with names that include prefix
        for lst in current_lists:
            delete_list(lst["id"])
            info(f"Deleted list: {lst['name']}")

def main():
    parser = argparse.ArgumentParser(description="Cloudflare Manager Script")
    parser.add_argument("action", choices=["run", "leave"], help="Choose action: run or leave")
    args = parser.parse_args()    
    cloudflare_manager = CloudflareManager(PREFIX)
    
    if args.action == "run":
        cloudflare_manager.update_resources()
    elif args.action == "leave":
        cloudflare_manager.delete_resources()
    else:
        error("Invalid action. Please choose either 'run' or 'leave'.")

if __name__ == "__main__":
    main()
```

**Comment by luxysiv** [comment]
The new script features exact replacement of changed domains and keeps advertising domains always active. It also helps reduce script run time with many redundant steps. Don't worry about empty lists. Later, your list increases the number of domains, the script will use those lists. 
![Screenshot_2024-08-04-20-26-05-120_com microsoft emmx](https://github.com/user-attachments/assets/64d9b5ad-7cda-42ba-be0d-3d6806a2e1b0)
![Screenshot_2024-08-04-20-25-43-274_com microsoft emmx](https://github.com/user-attachments/assets/d3c47227-dcf5-4302-bba4-a58e8cdcad11)

**Comment by LexterS999** [comment]
It's a little confusing and doing a lot of mess. I thought that bug was in my formatting script.

**Comment by luxysiv** [comment]
Because you tried running up to 254 lists at once on Cloudflare Gateway. The new script will always keep the highest number of 254 lists. If you don't like the new script, you can use the old script. It will be exactly 142 lists

**Comment by luxysiv** [comment]
Lists on Cloudflare Gateway are only valid when the rule is created containing the id of the lists. Therefore, in the process of creating new lists, those lists will not take effect immediately

**Comment by luxysiv** [comment]
@LexterS999 I will add 2 mode to run script. Default is older and advanced is newest.

**Comment by LexterS999** [comment]
def prioritize_domains(domains):
    prioritized_domains = {}
    priority_levels = ['high', 'medium', 'low']
    
    for domain in domains:
        priority = priority_levels[0]
        if domain in allowed_domains:
            priority = 'high'
        elif domain in important_domains:
            priority = 'medium'
        prioritized_domains[domain] = priority
    
    return prioritized_domains

# Использование модуля для приоритизации доменов
prioritized_domains = prioritize_domains(globbed_domains)

for domain, priority in prioritized_domains.items():
    create_dns_rule_with_tag(api_token, domain, block_action, description, priority)

**Comment by luxysiv** [comment]
What's it?

**Comment by LexterS999** [comment]
That's ideas for integrating into script.

**Comment by luxysiv** [comment]
> That's ideas for integrating into script.
In what part and what is its effect?
